name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install
          npm install -g allure-commandline --save-dev
      - name: Run Playwright tests
        run: |
          npx playwright install
          npx playwright test --reporter=dot
      - name: Upload Allure Results (if exists)
        run: |
          if [ -d "allure-results" ]; then
            echo "Allure results found, uploading."
            # Upload allure-results if it exists
            actions/upload-artifact@v2:
              name: allure-results
              path: allure-results
          else
            echo "No allure-results found, skipping upload."
          fi
      - name: Generate Allure Report
        run: |
          allure generate ./allure-results --clean -o ./allure-report
      - name: Upload Allure Report (if exists)
        run: |
          if [ -d "allure-report" ]; then
            echo "Allure report found, uploading."
            # Upload allure-report if it exists
            actions/upload-artifact@v2:
              name: allure-report
              path: allure-report
          else
            echo "No allure-report found, skipping upload."
          fi
